"""360 全景数据 → COLMAP 文本格式的公共 helper。

写出的目录结构（原地，与 garden_lonlat.yaml 完全一致）：

    <scene>/
    ├── imgs/                      软链 -> images/
    ├── images/                    原始
    ├── train.txt / test.txt       image_name stem，每行一个
    └── sparse/0/
        ├── cameras.txt            dummy PINHOLE（reader 在 default_camera_type=3 时忽略）
        ├── images.txt             qvec tvec NAME（每帧两行：第二行空，符合 COLMAP 规范）
        └── points3D.ply           真实点云软链 / 随机点云

关键点：
1. 走 ERP/LonLat 通路（yaml: default_camera_type: 3），cameras.txt 的内参字段不会被使用，
   reader 直接 fx=W、fy=H 计算 FoV（见 scene/dataset_readers.py 第 94-102 行）。
2. R/T 走 OpenCV/COLMAP 约定：world->cam，c2w[:3,1:3]*=-1 在 convention=='blender' 时启用。
3. read_extrinsics_text 对每张图都会读两行（第二行通常是 xys），所以必须给空行占位。
"""

from __future__ import annotations

import os
import shutil
from typing import Iterable

import numpy as np
from plyfile import PlyData, PlyElement


def rotmat_to_qvec(R: np.ndarray) -> np.ndarray:
    """COLMAP 同款的 rotmat -> [qw, qx, qy, qz]。"""
    Rxx, Ryx, Rzx, Rxy, Ryy, Rzy, Rxz, Ryz, Rzz = R.flat
    K = np.array(
        [
            [Rxx - Ryy - Rzz, 0, 0, 0],
            [Ryx + Rxy, Ryy - Rxx - Rzz, 0, 0],
            [Rzx + Rxz, Rzy + Ryz, Rzz - Rxx - Ryy, 0],
            [Ryz - Rzy, Rzx - Rxz, Rxy - Ryx, Rxx + Ryy + Rzz],
        ]
    ) / 3.0
    eigvals, eigvecs = np.linalg.eigh(K)
    qvec = eigvecs[[3, 0, 1, 2], np.argmax(eigvals)]
    if qvec[0] < 0:
        qvec = -qvec
    return qvec


def euler_xyz_to_matrix(angles_deg: Iterable[float]) -> np.ndarray:
    """xyz 内旋顺序 R = Rx @ Ry @ Rz，单位度。"""
    ax, ay, az = (np.deg2rad(a) for a in angles_deg)
    cx, sx = np.cos(ax), np.sin(ax)
    cy, sy = np.cos(ay), np.sin(ay)
    cz, sz = np.cos(az), np.sin(az)
    Rx = np.array([[1, 0, 0], [0, cx, -sx], [0, sx, cx]])
    Ry = np.array([[cy, 0, sy], [0, 1, 0], [-sy, 0, cy]])
    Rz = np.array([[cz, -sz, 0], [sz, cz, 0], [0, 0, 1]])
    return Rx @ Ry @ Rz


def c2w_to_qt(c2w: np.ndarray, convention: str = "opencv") -> tuple[np.ndarray, np.ndarray]:
    """4x4 c2w -> COLMAP 的 (qvec, tvec)。

    convention='blender' 时按 NeRF/Blender 约定先翻 [:3, 1:3]，再 invert 成 w2c。
    """
    M = np.asarray(c2w, dtype=np.float64).copy()
    if convention == "blender":
        M[:3, 1:3] *= -1.0
    elif convention != "opencv":
        raise ValueError(f"unknown convention: {convention}")
    w2c = np.linalg.inv(M)
    R = w2c[:3, :3]
    t = w2c[:3, 3]
    qvec = rotmat_to_qvec(R)
    return qvec, t


def write_cameras_txt(path: str, width: int, height: int, camera_id: int = 1) -> None:
    """写 dummy PINHOLE。default_camera_type=3 时这些数被 reader 忽略，
    但保留合法格式以便其他工具复用。"""
    fx, fy = float(width), float(height)
    cx, cy = width / 2.0, height / 2.0
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("# Camera list with one line of data per camera:\n")
        f.write("#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]\n")
        f.write(f"# Generated by tools/_pano_colmap_utils.py (PINHOLE dummy for ERP/LonLat)\n")
        f.write(f"{camera_id} PINHOLE {width} {height} {fx} {fy} {cx} {cy}\n")


def write_images_txt(
    path: str,
    frames: list[dict],
    camera_id: int = 1,
    observations: dict[int, list[tuple[float, float, int]]] | None = None,
) -> None:
    """frames: [{name, qvec(4,), tvec(3,)}].

    COLMAP 文本格式每张图占两行：
        IMAGE_ID QW QX QY QZ TX TY TZ CAMERA_ID NAME
        POINTS2D[] as (X, Y, POINT3D_ID)

    observations: 可选，image_id -> [(x, y, point3d_id), ...] 的 2D 观测列表。
    如果未提供则写空行。
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("# Image list with two lines of data per image:\n")
        f.write("#   IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME\n")
        f.write("#   POINTS2D[] as (X, Y, POINT3D_ID)\n")
        for i, fr in enumerate(frames, start=1):
            q = fr["qvec"]
            t = fr["tvec"]
            name = fr["name"]
            f.write(
                f"{i} {q[0]:.10f} {q[1]:.10f} {q[2]:.10f} {q[3]:.10f} "
                f"{t[0]:.10f} {t[1]:.10f} {t[2]:.10f} {camera_id} {name}\n"
            )
            if observations and i in observations:
                obs = observations[i]
                f.write(" ".join(f"{x:.2f} {y:.2f} {pid}" for x, y, pid in obs))
                f.write("\n")
            else:
                f.write("\n")


def write_points3d_txt(
    path: str,
    xyz: np.ndarray,
    rgb: np.ndarray | None = None,
    tracks: dict[int, list[tuple[int, int]]] | None = None,
) -> None:
    """写 COLMAP points3D.txt。

    tracks: 可选，point3d_id -> [(image_id, point2d_idx), ...] 的观测追踪。
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    n = len(xyz)
    if rgb is None:
        rgb = np.full((n, 3), 200, dtype=np.uint8)
    with open(path, "w") as f:
        f.write("# 3D point list with one line of data per point:\n")
        f.write("#   POINT3D_ID, X, Y, Z, R, G, B, ERROR, TRACK[] as (IMAGE_ID, POINT2D_IDX)\n")
        for i in range(n):
            x, y, z = xyz[i]
            r, g, b = int(rgb[i, 0]), int(rgb[i, 1]), int(rgb[i, 2])
            pid = i + 1
            track_str = ""
            if tracks and pid in tracks:
                track_str = " " + " ".join(f"{im} {p2d}" for im, p2d in tracks[pid])
            f.write(f"{pid} {x:.6f} {y:.6f} {z:.6f} {r} {g} {b} 0.0{track_str}\n")
    print(f"  points3D.txt: {n} points -> {path}")


def build_erp_observations(
    frames: list[dict],
    xyz: np.ndarray,
    width: int,
    height: int,
    min_dist: float = 0.2,
    max_obs_per_image: int = 20000,
    seed: int = 42,
) -> tuple[dict[int, list[tuple[float, float, int]]], dict[int, list[tuple[int, int]]]]:
    """将 3D 点投影到每张 ERP 图像上，构建 COLMAP 的 2D-3D 对应。

    Returns:
        observations: image_id -> [(u, v, point3d_id), ...]
        tracks:       point3d_id -> [(image_id, point2d_idx), ...]
    """
    W, H = float(width), float(height)
    observations: dict[int, list[tuple[float, float, int]]] = {}
    tracks: dict[int, list[tuple[int, int]]] = {}

    for img_id, fr in enumerate(frames, start=1):
        qvec = fr["qvec"]
        tvec = fr["tvec"]
        R = _qvec2rotmat(qvec)
        pts_cam = xyz @ R.T + tvec  # (N, 3)

        r = np.sqrt(np.sum(pts_cam ** 2, axis=-1))
        valid = r > min_dist

        lon = np.arctan2(pts_cam[:, 0], pts_cam[:, 2])
        lat = np.arcsin(np.clip(pts_cam[:, 1] / np.clip(r, 1e-8, None), -1, 1))

        u = (lon / np.pi + 1.0) * (W / 2.0)
        v = (lat * 2.0 / np.pi + 1.0) * (H / 2.0)

        in_bounds = valid & (u >= 0) & (u < W) & (v >= 0) & (v < H)
        indices = np.where(in_bounds)[0]

        if len(indices) > max_obs_per_image:
            rng = np.random.RandomState(seed + img_id)
            indices = rng.choice(indices, max_obs_per_image, replace=False)
            indices.sort()

        obs_list: list[tuple[float, float, int]] = []
        for p2d_idx, pt_idx in enumerate(indices):
            pid = int(pt_idx) + 1  # POINT3D_ID is 1-based
            obs_list.append((float(u[pt_idx]), float(v[pt_idx]), pid))
            tracks.setdefault(pid, []).append((img_id, p2d_idx))

        observations[img_id] = obs_list

    total_obs = sum(len(v) for v in observations.values())
    print(f"  ERP projection: {total_obs} observations across {len(observations)} images")
    return observations, tracks


def _qvec2rotmat(qvec: np.ndarray) -> np.ndarray:
    """COLMAP qvec [qw, qx, qy, qz] -> 3x3 rotation matrix."""
    w, x, y, z = qvec
    return np.array([
        [1 - 2*y*y - 2*z*z,     2*x*y - 2*w*z,     2*x*z + 2*w*y],
        [    2*x*y + 2*w*z, 1 - 2*x*x - 2*z*z,     2*y*z - 2*w*x],
        [    2*x*z - 2*w*y,     2*y*z + 2*w*x, 1 - 2*x*x - 2*y*y],
    ])


def write_split_txt(path: str, names_no_ext: Iterable[str]) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        for n in names_no_ext:
            f.write(f"{n}\n")


def ensure_imgs_symlink(scene_dir: str, images_subdir: str = "images", target: str = "imgs") -> None:
    src = os.path.join(scene_dir, images_subdir)
    dst = os.path.join(scene_dir, target)
    if not os.path.isdir(src):
        raise FileNotFoundError(f"原 images 目录不存在: {src}")
    if os.path.islink(dst):
        os.unlink(dst)
    elif os.path.isdir(dst):
        return
    elif os.path.exists(dst):
        raise RuntimeError(f"{dst} 已存在且不是目录或软链，请手动处理")
    os.symlink(images_subdir, dst)


def store_ply(path: str, xyz: np.ndarray, rgb: np.ndarray) -> None:
    """rgb 取值范围 [0, 255] uint8。"""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    dtype = [
        ("x", "f4"), ("y", "f4"), ("z", "f4"),
        ("nx", "f4"), ("ny", "f4"), ("nz", "f4"),
        ("red", "u1"), ("green", "u1"), ("blue", "u1"),
    ]
    normals = np.zeros_like(xyz)
    elements = np.empty(xyz.shape[0], dtype=dtype)
    attrs = np.concatenate([xyz, normals, rgb], axis=1)
    elements[:] = list(map(tuple, attrs))
    PlyData([PlyElement.describe(elements, "vertex")]).write(path)


def link_or_copy_ply(src_ply: str, dst_ply: str, prefer_symlink: bool = True) -> None:
    """把现成的 ply 放到 sparse/0/points3D.ply。优先软链，失败则拷贝。"""
    os.makedirs(os.path.dirname(dst_ply), exist_ok=True)
    if os.path.islink(dst_ply) or os.path.exists(dst_ply):
        os.remove(dst_ply)
    if prefer_symlink:
        try:
            os.symlink(os.path.abspath(src_ply), dst_ply)
            return
        except OSError:
            pass
    shutil.copy2(src_ply, dst_ply)


def normalize_ply_for_3dgs(src_ply: str, dst_ply: str) -> int:
    """把外部 ply 重新写一份，**保证带 nx/ny/nz 法线**（real2sim 的 fetchPly 要求）。

    只读 x/y/z 与 red/green/blue（若没有 RGB 则用灰色填充）。返回点数。
    360Roam 的 scene.ply 来自 CloudCompare，没有 normals，必须经过此函数。
    """
    plydata = PlyData.read(src_ply)
    v = plydata["vertex"]
    n = len(v["x"])
    xyz = np.vstack([v["x"], v["y"], v["z"]]).T.astype(np.float32)
    has_rgb = all(prop in v.data.dtype.names for prop in ("red", "green", "blue"))
    if has_rgb:
        rgb = np.vstack([v["red"], v["green"], v["blue"]]).T.astype(np.uint8)
    else:
        rgb = np.full((n, 3), 200, dtype=np.uint8)
    store_ply(dst_ply, xyz, rgb)
    return n


def random_pcd_from_camera_centers(
    cam_centers: np.ndarray,
    num_points: int = 200_000,
    expand: float = 3.0,
    seed: int = 0,
) -> tuple[np.ndarray, np.ndarray]:
    """根据相机包围盒外扩 N 倍生成随机点云。

    返回 (xyz [N,3] float32, rgb [N,3] uint8)。
    """
    rng = np.random.default_rng(seed)
    centers = np.asarray(cam_centers, dtype=np.float64)
    lo = centers.min(axis=0)
    hi = centers.max(axis=0)
    ctr = (lo + hi) / 2.0
    half = np.maximum((hi - lo) / 2.0, 1e-3) * expand
    lo_e = ctr - half
    hi_e = ctr + half
    xyz = rng.uniform(lo_e, hi_e, size=(num_points, 3)).astype(np.float32)
    rgb = rng.integers(0, 256, size=(num_points, 3), dtype=np.int32).astype(np.uint8)
    return xyz, rgb
